version: '3.8'

services:
  symfony-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-app
    volumes:
      - ./symfony:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    working_dir: /var/www/html

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
